version: '3.5'
services:
  mongo:
    image: mongo:3.7.9-jessie
    volumes:
      - ./runtime/mongo/data/db:/data/db
      - ./runtime/mongo/data/configdb:/data/configdb
    ports:
      - 27017:27017
